"""Install a ``scoutctl`` wrapper shim into ``~/.local/bin``.

The session driven by ``SKILL.md`` calls bare ``scoutctl`` (e.g.
``scoutctl action-items new-prefix``), but it inherits the user's login
PATH — *not* the launchd plist's ``EnvironmentVariables:PATH`` — and nothing
else puts ``scoutctl`` on that PATH. Without this shim the session silently
falls back to hand-minting action-item prefixes. See scout-plugin#99.

We write a tiny **wrapper** (not a version-pinned symlink) that execs the
scoutctl bound to the currently-loaded plugin checkout. ``install`` and
``upgrade`` both (re)write it, so it tracks the active plugin version across
updates — a symlink into a versioned marketplace dir would dangle on the
next update.

``~/.local/bin`` is the same directory the installed plists already trust in
their PATH, and is conventionally on macOS user PATHs (pip ``--user`` / pipx).
"""

from __future__ import annotations

from pathlib import Path

from scout.scripts.install_schedule_plist import resolve_scoutctl_bin

SHIM_NAME = "scoutctl"
# Sentinel in the generated wrapper so we only ever rewrite our own shim and
# never clobber a real `scoutctl` the user installed (pipx, global venv, …).
SHIM_MARKER = "# scout-plugin scoutctl shim"


def shim_dir(home: Path) -> Path:
    return home / ".local" / "bin"


def install_scoutctl_shim(*, home: Path | None = None, target_bin: Path | None = None) -> Path | None:
    """Write ``~/.local/bin/scoutctl`` wrapping the active plugin's scoutctl.

    Best-effort: returns the shim path on success, or ``None`` when the target
    scoutctl can't be resolved, ``~/.local/bin`` isn't writable, or a foreign
    (non-shim) ``scoutctl`` is already present there. Never raises — a missing
    shim degrades the session to manual prefix-minting (the pre-existing
    behavior), which is a soft fallback, not a hard failure.
    """
    home = home or Path.home()
    real = target_bin or resolve_scoutctl_bin()
    if not real.exists():
        return None

    d = shim_dir(home)
    try:
        d.mkdir(parents=True, exist_ok=True)
    except OSError:
        return None

    shim = d / SHIM_NAME
    # Leave anything we didn't write alone: a symlink, or a regular file that
    # lacks our marker, is presumed a user-managed scoutctl. Our own shim
    # carries the marker and is safe to refresh (re-point at the current venv).
    if shim.is_symlink():
        return None
    if shim.is_file():
        try:
            existing = shim.read_text(encoding="utf-8")
        except OSError:
            return None
        if SHIM_MARKER not in existing:
            return None

    script = (
        "#!/bin/sh\n"
        f"{SHIM_MARKER} — regenerated by `scoutctl bootstrap install/upgrade`.\n"
        "# Execs the scoutctl bound to the currently-loaded Scout plugin checkout.\n"
        f'exec "{real}" "$@"\n'
    )
    try:
        shim.write_text(script, encoding="utf-8")
        shim.chmod(0o755)
    except OSError:
        return None
    return shim
